# Generated by Django 3.1.2 on 2020-10-28 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Constellation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('symbolism', models.TextField(max_length=200)),
                ('num_main_stars', models.IntegerField()),
                ('brightest_star', models.CharField(max_length=50)),
            ],
        ),
    ]
