# Generated by Django 3.1.2 on 2020-10-28 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_planet'),
    ]

    operations = [
        migrations.AddField(
            model_name='constellation',
            name='planets',
            field=models.ManyToManyField(to='main_app.Planet'),
        ),
    ]
