# Generated by Django 3.1.2 on 2020-10-30 06:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_remove_star_date_observed'),
    ]

    operations = [
        migrations.AddField(
            model_name='constellation',
            name='date_observed',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
